### PR TITLE
Update LY2EN-micromodem-bom.csv

### PR DESCRIPTION
**Pull request by ido1990**
Removed R9 from line 4

### CODE REVIEW

**Comment by kareiva** [comment]
Please explain. Should it be 10k or 47k?

**Comment by ido1990** [comment]
This line is wrong:
47k,R5,R9,R_0805_2012Metric_Pad1.20x1.40mm_HandSolder,
The R9 shouldn't be there so I removed it.
If you open the file with Excel you'll see that the R9 is under the _Package_ column.
תמונה

**Comment by kareiva** [comment]
You are right about the format, although I think it was just a malformed way to say that both R5 and R9 are 47k (like R11 and R10 are comma separated 100k). Let me check if this is exactly this mistake and I will let you know.

**Comment by ido1990** [comment]
As far as I remember, R9 is not 47k
R5 is 47k because it replaced the trimmer.
As you wrote on the README:

> Set the 3296W trimmer to something around 47kOhm. Your resistance might vary here. **Once you're confident, you can replace it with a simple 47k resistor.**

**Comment by kareiva** [comment]
Thanks, although I am not 100% sure if the 47k is a perfect match for Baofeng or any other radio. It's just a wild-ass guess.

**Comment by ido1990** [comment]
> Thanks, although I am not 100% sure if the 47k is a perfect match for Baofeng or any other radio. It's just a wild-ass guess.

Ordered the PCB two days ago.
I will test and see.

**Pull request merged**
